language: go
dist: bionic

go:
  - "1.13.x"

services:
  - docker

env:
  matrix:
    - GO111MODULE=on
  global:
    - secure: vw0xtSTNedspQ9kjr/w2MMdK6+Uvf5vVzoM7bANpBf6fqaJq4ELB0YkMybMDSqME7155BAZqxhsRDS1oslmFWDIGAa+HhokPZf4UmroHgYQbxQWkGHX65st51Uldy3hBmdNyfUXZZp8ipeM527qujwnvAWKe4PxYXh1yvwpEtQZNHwpF6eWJnXkMInQzl0gUaa43Xg5B5wuDIXGO98MrnJToX6t1PGVF3y8uLhZsFHc7cWjt1ExUTIzc+K8nbBnn3wQvYITy0Qh7ykp63uCLmV8w3/mraS8IHTZukiEZaOCxcxldLAcrPvR6lZzuk3hNHlofUH9K9WkOm3cL2suF3pukK90fSbpiOYKEkk2UIdxAlN8zIsny33L+Quw5PqkBX7+HoPVkNlx3/OF+vRdr3kaGo6e5jt4nROGPMuwjdSq4UycyeEZIckOZ8+XtaDWIIQv9DlWSfAezVdXDWOCxI/NQvPWoYnA7sOUItjinIYzYbBeUCwafa60a0/+sc4OCgElxy8R2onazaXno8MdOdgixu74ZwxLT7OCFT4n3wxxXxxXnVuAe3NZ4x96bavrCcgsE1opuOWl7hscRwsmDdEyCoij7atWaOUyj49dxfntjbibiUoDy3VI4A3k3X2r0OexOsrgmpbNCEYZnMwv+jADAS470Vc6uq101lr8OXx0=
    - secure: UpNkDIGNTf8n4J1qnUdV7qQl0495Lg5+E2WVVZqnQC8N9a2L2ROEnEiVPCwt+Pozc2HdvSazNxPjfwo/MfnWZ2f7HTQEl0NHDb/KS7c+VJOPNqWe6mMUnfsblQ7bZfEthC4xK1nqQC6Urumhx6adS7Jnzr0hT38ecpHJ5pcc+WMEkKr7erqJbigE2bYOoLjrVBfA6M2sfej5nei51nw+eq6yH0eMDMxzpT4Se9GFXYdGYPOt+AMQdb+UcHQArFtcboti2Dai6IRr9EUd/lUqVfPagXYdpHWHFWGQ/kBCEXU6TY9DOIHRB0sieenIhGs4xIfxbwnU4kwHfOq265M4Pk55pRudyNJtu09DXt5k+6Fq9LTgXffVQi6LZ1TuamtwhM4xMxt65N1fxuPwD+TLhO5s/5rykMNWcbBANk9hT97B0sHtetL7VxLQLR6Kgc3/1e1vntPaDDT0wXbK85eLl0GY/p+HvT9njao7yl7mfbCN/YcDEXuERpZhEPuX4o7HORQZCxy1F951vnbGK99DDMh37ySLBUEy8mO+Ty4pQYBRoygk9LTj2pZptMPSYwu+z/Oc7sN2lVQNiuphQjJqb3TKbNsN8GdJJJil8XeX5uwxGosLda+yP4Jxqr7CcjyqnoBQeAcRQmyZJ807JS0xBmZeIIUZLj2Z4B9MqYIHuFk=

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u=evenh -p="$DOCKER_PASSWORD"

# calls goreleaser
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = linux
