/*
Copyright © 2019 Even Holthe

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package internal

import (
	"bufio"
	"io"
	"os"
	"strconv"

	"github.com/pkg/errors"
)

const header = `%%%% HASHDEEP-1.0
%%%% size,md5,filename`

const comment = `# Generated by az-blob-hashdeep`

type HashdeepEntry struct {
	size    int64
	md5hash string
	path    string
}

type HashdeepOutputFile struct {
	OutputFile string
	file       *os.File
	writer     *bufio.Writer
}

func (h *HashdeepOutputFile) Open() error {
	file, err := os.OpenFile(h.OutputFile, os.O_RDWR|os.O_CREATE|os.O_EXCL, 0755)

	if err != nil {
		return errors.Wrapf(err, "Error opening results file '%s", h.OutputFile)
	}

	h.file = file

	w := bufio.NewWriter(file)

	// Write header and comment
	_, _ = io.WriteString(w, header+"\n")
	_, _ = io.WriteString(w, comment+"\n")

	h.writer = w

	return nil
}

func (h HashdeepOutputFile) WriteEntry(e *HashdeepEntry) error {
	_, err := h.writer.WriteString(strconv.FormatInt(e.size, 10) + "," + e.md5hash + "," + e.path + "\n")

	if err != nil {
		return errors.Wrapf(err, "Error while writing entry to output file '%s'", h.OutputFile)
	}

	return nil
}

func (h *HashdeepOutputFile) Close() error {
	err := h.writer.Flush()
	if err != nil {
		return errors.Wrap(err, "Could not flush output writer")
	}

	err = h.file.Close()

	if err != nil {
		return errors.Wrapf(err, "Could not close results file '%s'", h.OutputFile)
	}

	return nil
}
